name: SFDX Code Scan Delta

on:
  push:
    branches:
      - main
      - '**'

jobs:
  installcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install CLI
        run: npm install @salesforce/cli --global

      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Verify SFDX CLI Installation
        run: sf --version

      - name: Verify SFDX Scanner Plugin Installation
        run: sf plugins --core

      - name: Install diffc
        run: |
          # Download and install diffc if it is available via URL or package
          wget https://example.com/path/to/diffc.tar.gz  # Replace with actual URL if necessary
          tar -xf diffc.tar.gz
          cd diffc
          ./configure
          make
          sudo make install

      - name: Verify diffc Installation
        run: diffc --version

      - name: Get Changed Files and Lines
        id: get-changed-lines
        run: |
          git fetch --unshallow || true
          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
            echo "Fetching changed files and lines between HEAD~1 and HEAD"
            diffc --unified=0 HEAD~1 HEAD > changes.diff

            # Extract filenames and line numbers from diffc output
            grep '^diff --git' changes.diff | sed 's/^diff --git a\//\n/g' | sed 's/ b\//\n/g' | awk '{print $1}' | sort -u > changed_files.txt
            awk '/^@@/ {flag=1; next} /^diff/ {flag=0} flag' changes.diff > temp_changes.txt
          else
            echo "No previous commit to compare to." > changes.diff
            echo "No previous commit to compare to." > changed_files.txt
            echo "No previous commit to compare to." > temp_changes.txt
          fi
          echo "Changes Diff:"
          cat changes.diff
          echo "Changed Files:"
          cat changed_files.txt

      - name: Run SFDX Scanner on Entire Codebase
        if: success()
        run: |
          sf scanner:run --target "." --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
          echo "SFDX Scanner Report:"
          cat scanner-report.csv

      - name: Filter Report for Committed Lines
        if: success()
        run: |
          # Create a file to store filtered report
          touch filtered-report.csv
          echo "File,Line,Column,Severity,Message" > filtered-report.csv

          # Read the original report and filter lines based on changes
          while IFS=, read -r file line column severity message; do
            if grep -q "$file" temp_changes.txt; then
              if grep -q "$line" temp_changes.txt; then
                echo "$file,$line,$column,$severity,$message" >> filtered-report.csv
              fi
            fi
          done < <(tail -n +2 scanner-report.csv) # Skip header line

          echo "Filtered Report:"
          cat filtered-report.csv

      - name: Encode CSV file to Base64
        if: success()
        id: encode_file
        run: |
          if [ -f filtered-report.csv ]; then
            base64 filtered-report.csv | tr -d '\n' > encoded_report.txt
          else
            echo "Filtered report CSV file not found."
            exit 1
          fi

      - name: Install mailx
        run: sudo apt-get install -y mailutils

      - name: Get Repository and Branch Info
        id: get-info
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
          FILE_TITLE="Code Scanner Delta Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV

      - name: Upload Scanner Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_TITLE }}
          path: filtered-report.csv

      - name: Get Pusher's Email
        id: get-pusher-email
        run: |
          COMMIT_SHA=${{ github.sha }}
          REPO=${{ github.repository }}
          PUSHER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            "https://api.github.com/repos/${REPO}/commits/${COMMIT_SHA}" | jq -r '.commit.committer.email')
          echo "PUSHER_EMAIL=${PUSHER_EMAIL}" >> $GITHUB_ENV

      - name: Upload CSV Report to Salesforce
        if: success()
        run: |
          if [ -s encoded_report.txt ]; then
            contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "Title": "'"${{ env.FILE_TITLE }}"'",
                "PathOnClient": "filtered-report.csv",
                "VersionData": "'"$(cat encoded_report.txt)"'"
              }')
            echo "Response: $contentDocumentResponse"
            
            contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
            if [ -z "$contentVersionId" ]; then
              echo "Error: Failed to upload file. No ContentVersionId found."
              exit 1
            fi
            echo "ContentVersionId: $contentVersionId"
            
            contentDocumentResponse=$(curl -X GET https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/$contentVersionId \
              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}")
            echo "ContentDocument Response: $contentDocumentResponse"
            
            contentDocumentId=$(echo $contentDocumentResponse | jq -r '.ContentDocumentId // empty')
            if [ -z "$contentDocumentId" ]; then
              echo "Error: Failed to retrieve ContentDocumentId. No ContentDocumentId found."
              exit 1
            fi
            echo "ContentDocumentId: $contentDocumentId"
          else
            echo "No filtered report generated, skipping upload."
          fi
        env:
          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        shell: bash

      - name: Send Email with actions-send-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 'smtp.gmail.com'
          server_port: '587'
          username: ${{ secrets.GMAIL_EMAIL }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from: ${{ secrets.GMAIL_EMAIL }}
          subject: 'SFDX Code Scan Delta Report'
          body: 'Please find the attached SFDX Code Scan Delta Report.'
          to: ${{ env.PUSHER_EMAIL }}, ${{ secrets.GMAIL_EMAIL }}
          attachments: filtered-report.csv