on:
  push:
    branches: "**"

jobs:
  installcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install CLI
        run: npm install @salesforce/cli --global

      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Verify SFDX CLI Installationn
        run: sf --version

      - name: Verify SFDX Scanner Plugin Installation
        run: sf plugins --core

      - name: Get changed files and lines
        id: get-changes
        run: |
          # Check if the repository is shallow and unshallow if necessary
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            echo "Repository is shallow, unshallowing..."
            git fetch --unshallow
          else
            echo "Repository is not shallow, skipping unshallow."
          fi

          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
            echo "Fetching changed files and lines between HEAD~1 and HEAD"
            git diff --unified=0 HEAD~1 HEAD > changes.diff
          else
            echo "No previous commit to compare to." > changes.diff
          fi

          cat changes.diff

      - name: Extract changed lines, create temp file, and scan
        if: success()
        run: |
          files=$(grep -E '^\+\+\+ b/.*(\.cls|\.lwc)$' changes.diff | sed 's/+++ b\///')

          if [ -z "$files" ]; then
            echo "No changed .cls or .lwc files detected."
            exit 0  # Gracefully exit if no relevant files are changed
          fi

          while IFS= read -r file; do
            echo "Processing file: $file"
            
            # Extract the actual changed lines with line numbers for the specific file
            changed_lines_with_numbers=$(grep -A 1000 "$file" changes.diff | grep '^@@' -A 1 | grep '^+' | grep -v '+++' | cut -d'+' -f2-)
            line_numbers=$(grep -A 1000 "$file" changes.diff | grep '^@@' | awk '{print $2}' | cut -d',' -f1 | sed 's/-//')
            
            if [ -n "$changed_lines_with_numbers" ]; then
              echo "Changed lines in $file:"
              echo "$changed_lines_with_numbers"
              
              temp_file="temp_${file//\//_}"
              echo "/* Temporary file for changed lines scan */" > "$temp_file"

              # Add ApexDoc for the temporary wrapper class
              echo "/**" >> "$temp_file"
              echo " * @description Temporary wrapper class generated for scanning changed lines." >> "$temp_file"
              echo " */" >> "$temp_file"
              echo "public class TempWrapperClass {" >> "$temp_file"

              # Add ApexDoc for the temporary method
              echo "    /**" >> "$temp_file"
              echo "     * @description Temporary method to encapsulate the changed lines for scanning." >> "$temp_file"
              echo "     */" >> "$temp_file"
              echo "    public static void tempMethod() {" >> "$temp_file"
              echo "        /* Begin of extracted changed lines */" >> "$temp_file"
              echo "$changed_lines_with_numbers" >> "$temp_file"
              echo "        /* End of extracted changed lines */" >> "$temp_file"
              echo "    }" >> "$temp_file"

              # Handle unbalanced braces as before...
              echo "}" >> "$temp_file"

              echo "Created temporary file with method structure: $temp_file"
              
              # Run the SFDX scanner on the temporary file
              echo "Running SFDX scanner on temporary file $temp_file"
              sf scanner:run --target "$temp_file" --format "csv" --outfile "scanner-report-$temp_file.csv" || { echo "Scanner run failed"; exit 1; }

              if [ -s "scanner-report-$temp_file.csv" ]; then
                echo "Scanner report generated for $temp_file."
                
                # Trim file paths as before...

                # Add line numbers to the scanner report
                echo "Adding changed line numbers to the report."
                paste -d, <(echo "$line_numbers") "scanner-report-$temp_file.csv" > "scanner-report-$temp_file-with-lines.csv"
                
                echo "File paths trimmed and line numbers added in scanner-report-$temp_file-with-lines.csv."
              else
                echo "No scanner report generated for $temp_file."
                exit 0
              fi

              # Clean up as before...
            else
              echo "No relevant changes detected in $file."
            fi
          done <<< "$files"

        env:
          SF_LAZY_LOAD_MODULES: "true"
          SF_AUTOUPDATE_DISABLE: "true"
          SF_DISABLE_AUTOUPDATE: "true"

      - name: Install mailx
        run: sudo apt-get install -y mailutils

      - name: Get Repository and Branch Info
        id: get-info
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
          FILE_TITLE="SFDX_Code_Scan_Delta_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}.csv"
          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV

      - name: Upload Scanner Report and Rules as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SFDX_Code_Scan_Delta
          path: |
            scanner-report-*.csv

      - name: Get Pusher's Email
        id: get-pusher-email
        run: |
          COMMIT_SHA=${{ github.sha }}
          REPO=${{ github.repository }}
          PUSHER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            "https://api.github.com/repos/${REPO}/commits/${COMMIT_SHA}" | jq -r '.commit.committer.email')
          echo "PUSHER_EMAIL=${PUSHER_EMAIL}" >> $GITHUB_ENV

      - name: Encode CSV report to base64
        run: |
          report_file=$(find . -name "scanner-report-*.csv" | head -n 1)
          if [ -s "$report_file" ]; then
            base64 "$report_file" > encoded_report.txt
          else
            echo "No scanner report found."
            exit 0  # Gracefully exit if no report was found
          fi

      - name: Upload CSV Report to Salesforce
        if: success()
        run: |
          if [ -s encoded_report.txt ]; then
            # Read the base64 content from the file and escape special characters for JSON
            ENCODED_DATA=$(cat encoded_report.txt | tr -d '\n')
            
            # Upload the encoded report to Salesforce
            contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "Title": "'"${{ env.FILE_TITLE }}"'",
                "PathOnClient": "scanner-report.csv",
                "VersionData": "'"$ENCODED_DATA"'"
              }')
              
            echo "Response: $contentDocumentResponse"
              
            echo "Response: $contentDocumentResponse"
            
            # Extract the ContentVersionId from the response
            contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
            if [ -z "$contentVersionId" ]; then
              echo "Error: Failed to upload file. No ContentVersionId found."
              exit 1
            fi
            echo "ContentVersionId: $contentVersionId"
            
            # Get the ContentDocumentId
            contentDocumentResponse=$(curl -X GET https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/$contentVersionId \
              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}")
            echo "ContentDocument Response: $contentDocumentResponse"
            
            contentDocumentId=$(echo $contentDocumentResponse | jq -r '.ContentDocumentId // empty')
            if [ -z "$contentDocumentId" ]; then
              echo "Error: Failed to retrieve ContentDocumentId. No ContentDocumentId found."
              exit 1
            fi
            echo "ContentDocumentId: $contentDocumentId"
          else
            echo "No encoded report found, skipping upload."
          fi
        env:
          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
