name: SFDX Code Scan Delta with Temporary Workspace
 
on:
  push:
    branches:
      - '**'
 
permissions:
  contents: write
  pull-requests: write
 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into temporary directory
        uses: actions/checkout@v3
        with:
          path: temp_workspace
 
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
 
      - name: Install CLI
        run: npm install @salesforce/cli --global
 
      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner
 
      - name: Verify SFDX CLI Installation
        run: sf --version
 
      - name: Verify SFDX Scanner Plugin Installation
        run: sf plugins --core
 
      - name: Get changed files in temporary workspace
        id: get-changes
        run: |
          cd temp_workspace
          git fetch --unshallow || true
          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
            echo "Fetching changed files between HEAD~1 and HEAD"
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit to compare to." > changed_files.txt
          fi
          cat changed_files.txt
 
      - name: Run SFDX Scanner on Changed Files
        if: success()
        run: |
          cd temp_workspace
          files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
          echo "Files to scan: $files"
          if [ -n "$files" ]; then
            sf scanner:run --target "$files" --format "csv" --outfile "scanner-report.csv" || { echo "Scanner run failed"; exit 1; }
          else
            echo "No relevant files changed."
            touch scanner-report.csv
          fi
        env:
          SF_LAZY_LOAD_MODULES: 'true'
          SF_AUTOUPDATE_DISABLE: 'true'
          SF_DISABLE_AUTOUPDATE: 'true'
 
      - name: Save scanner report as an artifact for next steps
        uses: actions/upload-artifact@v3
        with:
          name: scanner-report
          path: temp_workspace/scanner-report.csv
 
  quality_gate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download scanner report artifact
        uses: actions/download-artifact@v3
        with:
          name: scanner-report
 
      - name: Encode CSV file to Base64
        id: encode_file
        run: |
          if [ -f scanner-report.csv ]; then
            base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
          else
            echo "Scanner report CSV file not found."
            exit 1
          fi
 
      - name: Check Scanner Report Severity
        id: check_severity
        run: |
            if [ ! -f "scanner-report.csv" ]; then
              echo "Scanner report not found!"
              echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
              echo "::error file=scanner-report.csv::Scanner report not found!"
              exit 1
            fi
            echo "Checking scanner report content:"
            cat scanner-report.csv  # Print CSV content to see what's inside
            SEVERITY_FAIL_COUNT=$(awk -F',' '{gsub(/^ *| *$/, "", $2); if($2 == "\"3\"") count++} END {print count}' scanner-report.csv)
            SEVERITY_FAIL_COUNT=${SEVERITY_FAIL_COUNT:-0}  # Default to 0 if SEVERITY_FAIL_COUNT is empty
            echo "Severity 3 Count: $SEVERITY_FAIL_COUNT"
            if [ "$SEVERITY_FAIL_COUNT" -gt 0 ]; then
              echo "Quality gate failed due to high severity issues."
              echo "QUALITY_GATE_STATUS=FAILED" >> $GITHUB_ENV
              echo "::error::Quality gate failed due to high severity issues."
              exit 1  # Fail the workflow and block the commit
            else
              echo "Quality gate passed."
              echo "QUALITY_GATE_STATUS=PASSED" >> $GITHUB_ENV
              echo "::notice::Quality gate passed."
            fi
 
      - name: Upload CSV Report to Salesforce
        if: success() && env.QUALITY_GATE_STATUS == 'PASSED'  # Only upload if quality gate passed
        run: |
          if [ -s encoded_report.txt ]; then
            contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
              -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "Title": "Code Scanner Delta Report",
                "PathOnClient": "scanner-report.csv",
                "VersionData": "'"$(cat encoded_report.txt)"'"
              }')
            echo "Response: $contentDocumentResponse"
            contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
            if [ -z "$contentVersionId" ]; then
              echo "Error: Failed to upload file. No ContentVersionId found."
              exit 1
            fi
            echo "ContentVersionId: $contentVersionId"
          else
            echo "No scanner report generated, skipping upload."
          fi
        env:
          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        shell: bash
 
  commit_and_push:
    runs-on: ubuntu-latest
    needs: quality_gate
    if: ${{ needs.quality_gate.outputs.quality_gate_status == 'PASSED' }}
    steps:
      - name: Checkout code in temporary directory
        uses: actions/checkout@v3
        with:
          path: temp_workspace
          fetch-depth: 0
 
      - name: Commit and push changes
        run: |
          cd temp_workspace
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Committing changes after quality gate passed"
          git push