name: SFDX Code Scan Delta

on: push

jobs:
  sfdx_scan_delta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last 2 commits

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install SFDX CLI
      run: npm install sfdx-cli --global

    - name: Identify changed lines
      id: diff
      run: |
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          git diff --unified=0 HEAD~1 HEAD -- force-app/main/default/classes/Talent_Bench_Data.cls > changed_lines.txt
        else
          echo "No previous commit found. Assuming this is the first commit."
          echo "" > changed_lines.txt
        fi
      continue-on-error: true

    - name: Run SFDX Scanner
      run: |
        sfdx scanner:run --target force-app/main/default/classes/Talent_Bench_Data.cls --format csv --outfile scanner-report.csv

    - name: Filter Scanner Report for Changed Lines
      run: |
        python filter_scanner_report.py changed_lines.txt scanner-report.csv filtered-scanner-report.csv

    - name: Upload filtered report
      uses: actions/upload-artifact@v2
      with:
        name: filtered-scanner-report
        path: filtered-scanner-report.csv