name: SFDX PMD Delta Analysis on Changed Lines

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  sfdx-pmd-delta-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          sudo npm install -g sfdx-cli

      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2Fpmd-6.40.0/pmd-bin-6.40.0.zip
          unzip pmd-bin-6.40.0.zip
          export PMD_HOME=$PWD/pmd-bin-6.40.0
          export PATH=$PMD_HOME/bin:$PATH

      - name: Authenticate to Salesforce
        run: |
          sfdx auth:accesstoken:store --instanceurl https://login.salesforce.com --access-token ${{ secrets.SF_ACCESS_TOKEN }}

      - name: Get changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only HEAD origin/main > changed_files.txt

      - name: Get changed lines
        id: diff
        run: |
          git diff HEAD^ HEAD > changes.diff
          echo "Changed lines extracted."

      - name: Extract changed lines from .cls files
        id: extract_lines
        run: |
          grep -E '^\+[^+]' changes.diff | sed -e 's/^\+//' > changed_lines.txt
          echo "Extracted changed lines."

      - name: Create temporary directory for filtered code
        run: mkdir filtered_code

      - name: Apply changed lines to code
        run: |
          while IFS= read -r line; do
            if [[ -n "$line" ]]; then
              # This assumes your codebase is structured to allow extraction of changed lines.
              # Adjust the following command to fit your needs.
              grep -F "$line" > filtered_code/filtered_$(basename "$line")
            fi
          done < changed_lines.txt
          echo "Filtered code based on changed lines."

      - name: Run SFDX Scanner on changed lines
        run: |
          sfdx scanner:run --sourcepath filtered_code --ruleset pmd --format csv --output sfdx_scanner_report.csv
        env:
          PMD_HOME: ${{ env.PMD_HOME }}

      - name: Upload SFDX Scanner report
        uses: actions/upload-artifact@v3
        with:
          name: sfdx-scanner-report
          path: sfdx_scanner_report.csv

      - name: Upload changed lines report
        uses: actions/upload-artifact@v3
        with:
          name: changed-lines-report
          path: changed_lines.txt