# .github/workflows/sfdx-scan.yml

name: SFDX Scan Code

on:
  push:
    branches:
      - main
      - '**'

jobs:
  check-run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Existing Run
        id: check_flag
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          ISSUE_TITLE="Workflow Run - ${BRANCH_NAME}"
          ISSUE_EXISTS=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&title=${ISSUE_TITLE}" | jq '. | length')
          if [ "$ISSUE_EXISTS" -gt 0 ]; then
            echo "Issue exists. Skipping workflow."
            exit 1
          else
            echo "No issue found. Proceeding with workflow."
          fi

      - name: Create Flag Issue
        if: success()
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          ISSUE_TITLE="Workflow Run - ${BRANCH_NAME}"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST -d '{"title":"'"${ISSUE_TITLE}"'","body":"This issue indicates that the workflow has run for this branch."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues"

  installcli:
    runs-on: ubuntu-latest
    needs: check-run-once
    if: success()  # Only run if the check-run-once job succeeds

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install CLI
        run: npm install @salesforce/cli --global
      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner
      - name: Verify SFDX CLI Installation
        run: sf --version
      - name: Verify SFDX Scanner Plugin Installation
        run: sf plugins --core
      - name: Run SFDX Scanner
        run: |
          sf scanner:run --target "force-app/main/default/classes/**/*.cls,force-app/main/default/lwc" --format "csv" --outfile "scanner-report.csv"
        env:
          SF_LAZY_LOAD_MODULES: 'true'
          SF_AUTOUPDATE_DISABLE: 'true'
          SF_DISABLE_AUTOUPDATE: 'true'
      - name: Encode CSV file to Base64
        id: encode_file
        run: |
          base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get Repository and Branch Info
        id: get_info
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          COMMIT_LABEL=$(git log -1 --pretty=format:'%s')
          FILE_TITLE="Code Scanner Overall Report_${REPO_NAME}_${BRANCH_NAME}_${COMMIT_LABEL}"
          echo "FILE_TITLE=${FILE_TITLE}" >> $GITHUB_ENV
      - name: Upload Scanner Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_TITLE }}
          path: scanner-report.csv
      - name: Upload CSV Report to Salesforce
        run: |
          contentDocumentResponse=$(curl -X POST https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
            -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "Title": "'"${{ env.FILE_TITLE }}"'",
              "PathOnClient": "scanner-report.csv",
              "VersionData": "'"$(cat encoded_report.txt)"'"
            }')
          echo "Response: $contentDocumentResponse"
          contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
          if [ -z "$contentVersionId" ]; then
            echo "Error: Failed to upload file. No ContentVersionId found."
            exit 1
          fi
          echo "ContentVersionId: $contentVersionId"
          contentDocumentResponse=$(curl -X GET https://individual-fc-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/$contentVersionId \
            -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}")
          echo "ContentDocument Response: $contentDocumentResponse"
          contentDocumentId=$(echo $contentDocumentResponse | jq -r '.ContentDocumentId // empty')
          if [ -z "$contentDocumentId" ]; then
            echo "Error: Failed to retrieve ContentDocumentId. No ContentDocumentId found."
            exit 1
          fi
          echo "ContentDocumentId: $contentDocumentId"
        env:
          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        shell: bash